Crud create
kana2212/MyBatis-Demo pull request #3
Opened 2023-07-04 01:33 UTC by kana2212

不要ファイル削除

2023-07-04 02:12 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/MemberApplication.java
> +@Configuration
こちら試行錯誤しているときにつけたのだと思うのですが、現状のコードなら無くても動くと思います。

2023-07-04 02:12 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/entity/MemberForm.java
> +    int id;
```suggestion
    private int id;
```

2023-07-04 02:12 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/entity/MemberForm.java
> +    String name;
```suggestion
    private String name;
```

2023-07-04 02:12 UTC, yoshi-koyama commented on MyBatisMemberApplication.java
PRのタイトルなのですが実態に沿った名前に変更しましょう！
<img width="320" alt="スクリーンショット 2023-07-04 11 10 10" src="https://github.com/kana2212/MyBatis-Demo/assets/62045457/6fb35c7c-1996-4fdd-88cc-55eacfbe209b">

2023-07-04 02:12 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/MemberServiceImpl.java
> +    @Autowired
コンストラクタ1つの場合、Autowiredは省略可能です！

2023-07-04 02:12 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/controller/MemberController.java
> +                .path("/members/{id}")
`/members/{id}`
でなく
`/members/1`
のように実際に採番されたIDがLocationヘッダーの値として返されるように実装しましょう！

2023-07-04 02:12 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/controller/MemberController.java
> +        return ResponseEntity.created(url).body("successfully created");
レスポンスボディですが、
```json
{
  "message": "successfully created"
}
```
のようなJSON形式にしてみてほしいです！

2023-07-04 02:52 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/MemberApplication.java
> +@Configuration
a297478bd46043a1783b18f12f0087433c7cd5c4
対応しました！

2023-07-04 02:57 UTC, kana2212 commented on MyBatisMemberApplication.java
POST createに変更しました。

2023-07-04 04:53 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/entity/MemberForm.java
> +    String name;
int id;
    private int id;
    @NotEmpty
    String name;
修正しました。

2023-07-04 04:55 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/controller/MemberController.java
> +                .path("/members/{id}")
src/main/java/com/example/MyBatisMember/controller/MemberController.java
こんな感じで修正しましたがどうでしょうか？

2023-07-04 05:13 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/controller/MemberController.java
> +        return ResponseEntity.created(url).body("successfully created");
https://github.com/kana2212/MyBatis-Demo/blob/4080664c5abf3781ade3557e1f39a39892592117/src/main/java/com/example/MyBatisMember/controller/MemberController.java#L39-L46
https://github.com/kana2212/MyBatis-Demo/assets/121325913/2c6722c8-be92-4ef7-b3a4-58ddc0910242
対応して修正しました。

2023-07-04 11:46 UTC, yoshi-koyama commented on MyBatisMemberApplication.java
個人的には日本語がいいですね。
また登録機能に加えて読み取り系のAPIの実装もしているので、私なら
```
読み取り系APIと登録APIの実装
```
のようにするかなと思いました。

2023-07-04 11:47 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/entity/MemberForm.java
> +    int id;
こちらの対応状況いかがですか？

2023-07-04 11:47 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/entity/MemberForm.java
> +    int id;
このコミットで対応していますね。

2023-07-04 11:47 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/entity/MemberForm.java
> +    String name;
対応コミット
https://github.com/kana2212/MyBatis-Demo/pull/3/commits/4080664c5abf3781ade3557e1f39a39892592117

2023-07-04 11:48 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/entity/MemberForm.java
> +    String name;
ちなみに、

int id;
private int id;
@notempty
String name;

こちらですがGitHubのMarkdownの記法であるコードブロックとシンタクスハイライトを使うとよいです。

```java
private int id;
@NotEmpty
private String name;
```

2023-07-04 11:49 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/entity/MemberForm.java
> +    String name;
このようにバックティックを使います。
<img width="772" alt="スクリーンショット 2023-07-04 20 48 56" src="https://github.com/kana2212/MyBatis-Demo/assets/62045457/8fb701b5-013f-4271-8e8e-a4a23e084f66">

2023-07-04 11:49 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/MemberServiceImpl.java
> +    @Autowired
対応コミット
https://github.com/kana2212/MyBatis-Demo/pull/3/commits/4080664c5abf3781ade3557e1f39a39892592117

2023-07-04 11:51 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/controller/MemberController.java
> +                .path("/members/{id}")
いいと思います！
動作確認してレスポンスヘッダーにLocationがあることを確認しましょう。
また、Locationの値に`/members/1`のように採番された値であることを確認してください！

2023-07-04 11:58 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/controller/MemberController.java
> +        return ResponseEntity.created(url).body("successfully created");
Mapにできていますね！
動作確認結果も貼ってくれると安心です！

2023-07-05 00:56 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/entity/MemberForm.java
> +    int id;
更新したコミットハッシュを貼れば良かったのですね！ありがとうございます。

2023-07-05 00:57 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/entity/MemberForm.java
> +    String name;
ご指摘ありがとうございます。Markdownもう少し勉強しておきます。

2023-07-05 01:01 UTC, kana2212 commented on MyBatisMemberApplication.java
なぜか英語縛りをしていました。
「読み取りと登録APIの実装」と纏めました。

2023-07-05 01:05 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/controller/MemberController.java
> +        return ResponseEntity.created(url).body("successfully created");
動作確認はこちらです。
https://github.com/kana2212/MyBatis-Demo/assets/121325913/2c6722c8-be92-4ef7-b3a4-58ddc0910242

2023-07-05 01:14 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/controller/MemberController.java
> +                .path("/members/{id}")
確認取れました。
合っていますでしょうか？
![スクリーンショット (93)](https://github.com/kana2212/MyBatis-Demo/assets/121325913/3d9630bb-7504-46f3-97de-f484c35a5ca0)

2023-07-05 02:16 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/controller/MemberController.java
> +        return ResponseEntity.created(url).body("successfully created");
OKです！

2023-07-05 02:19 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/controller/MemberController.java
> +        URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")
このPRで対応しなくてよいですが、
UriComponentsBuilderを引数にして、"http://localhost:8080"とハードコードしないよう実装してもいいかなと思いました。

http://terasolunaorg.github.io/guideline/current/ja/ArchitectureInDetail/WebServiceDetail/REST.html
> リンク情報に設定するURIを組み立てるため、Spring MVCから提供されているorg.springframework.web.util.UriComponentsBuilderクラスをメソッドの引数に指定する。

2023-07-05 02:19 UTC, yoshi-koyama commented on src/main/java/com/example/MyBatisMember/entity/Member.java
> +    private String age;
```suggestion
    private int age;
```
ではないでしょうか？

2023-07-05 14:40 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/controller/MemberController.java
> +        URI url = UriComponentsBuilder.fromUriString("http://localhost:8080")
対応して修正しました。
0d94c1ecb8230f49937ce5a8cedc06bc54d66847

2023-07-05 14:42 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/entity/Member.java
> +    private String age;
凡ミスしていましたすみません。修正しました。
0d94c1ecb8230f49937ce5a8cedc06bc54d66847

2023-07-05 15:05 UTC, yoshi-koyama approved these changes

2023-07-08 03:09 UTC, Shibata0806 requested changes
@kana2212 
実装お疲れ様です！
概ね問題ないと思います！
気になる点、2箇所にコメントしましたので、ご確認お願いします！

更新と削除のAPIを叩いているスクリーンショットも貼っておいていただけたら安心ですね！

2023-07-08 03:09 UTC, Shibata0806 commented on src/main/java/com/example/MyBatisMember/entity/Member.java
> +@EqualsAndHashCode
[ask]
今回の実装で、`@EqualsAndHashCode`を追加した意図としては何かありましたでしょうか？
これがないとupdate、deleteができなかったでしょうか？？
（`@EqualsAndHashCode`があっても問題ないとは思いますが気になりました）

2023-07-08 03:25 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/entity/Member.java
> +@EqualsAndHashCode
validationを考えていた時に試しにつけて消し忘れていました！

2023-07-08 04:11 UTC, kana2212 commented on src/main/java/com/example/MyBatisMember/mapper/MemberMapper.java
> +    void updateMemberById(int id, String name);
対応して修正しました。
318baca4a25659ae1f940938e884cd6d43927d81

2023-07-08 11:01 UTC, Shibata0806 approved these changes

2023-07-08 11:22 UTC, kana2212 commented
登録、更新、削除を実装

2023-07-08 11:22 UTC, merged